micronaut:
  application:
    name: pixChallenge
  server:
    port: 8082
datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/casa_codigo?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${DB_PASSWORD:8785491}
    schema-generate: CREATE_DROP
    dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true
jpa.default.properties.hibernate.hbm2ddl.auto: update
