micronaut:
  application:
    name: pixChallenge

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/pix?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${DB_PASSWORD:8785491}
    schema-generate: CREATE_DROP
    dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
